### ISSUE TITLE
Filter "Creative Cloud" from the APIs list that appears at the bottom of /creative-cloud/

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeDocs/cc-developer-platform-pages#50]
On:
https://www.adobe.io/creative-cloud/

In the card list of APIs toward the bottom of the page, "Creative Cloud" appears, which is effectively just a link back to the page the viewer is already on, creating a loop.

Previously, this card was filtered from the list. We'd like that filter back in place.

**Comment by icaraps** [comment]
This was fixed with https://github.com/AdobeDocs/dev-site-product-index/commit/cd3a01008a8d79a914a15a5cb37c4e83391cbae6

Feel free to order the product cards differently by using the product id like I did in the commit above.
